In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/breast_cancer.csv')
X = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [ ]:
count = df.isnull().sum()
print(count)

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [ ]:
print(X_train)

[[ 3  1  1 ...  1  1  1]
 [ 7  9  4 ...  5  3  3]
 [ 5  2  4 ...  1  1  1]
 ...
 [10  5  7 ...  3  3  8]
 [ 4  1  1 ...  2  1  1]
 [10 10 10 ...  8  8  8]]


In [ ]:
print(y_train)

[2 4 2 4 2 2 2 4 4 2 2 2 2 2 2 4 2 2 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 4 2 2 4
 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 4 2 4 2 4 4 2 2 2 2 4 4 4 2 2 4 2 2 4 2 4
 2 2 2 4 2 2 4 2 4 2 2 2 2 2 2 2 2 2 2 4 4 2 2 4 2 4 4 2 2 2 2 4 2 4 2 4 2
 2 2 4 2 4 4 2 2 2 2 2 4 2 2 2 4 2 2 4 2 2 4 4 2 2 2 2 4 2 4 2 2 2 2 2 2 2
 2 2 2 4 4 2 4 2 2 2 2 4 2 4 2 2 2 4 2 4 4 2 2 2 2 2 4 2 2 2 2 2 4 2 4 2 2
 2 4 2 2 4 2 4 2 4 4 4 4 2 2 4 4 4 2 2 4 2 2 4 4 2 4 2 2 2 2 2 4 2 4 2 2 2
 2 4 2 2 4 2 2 4 2 2 2 4 2 4 2 4 2 2 4 4 2 2 2 4 2 4 4 2 2 4 2 2 2 4 2 4 4
 2 2 2 2 2 2 2 2 4 2 2 4 2 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 4 2 2 2 4 4 2 4 4
 2 2 4 2 2 2 2 4 4 4 2 2 2 2 4 2 2 2 4 2 2 2 2 2 4 2 2 2 2 4 2 2 2 4 2 2 2
 2 4 4 2 2 4 2 4 2 2 2 4 2 2 2 4 2 4 2 2 2 4 2 2 4 4 4 2 4 2 2 4 2 4 2 2 2
 2 4 2 2 2 2 2 4 2 2 2 2 2 4 2 2 2 4 2 2 4 2 2 2 4 2 4 2 2 4 2 2 2 4 2 4 4
 4 2 2 2 2 4 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 4 4 2 2 2 4 4 4 2 4 2 4 2 2
 2 4 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 4 2 2 2 4 4 2 2 2 2 2 4 2 2 4 4 4 4 4 2
 2 2 2 2 2 4 2 4 2 2 2 2 

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 42)
lr.fit(X,y)

LogisticRegression(random_state=42)

In [ ]:
print(lr.predict([[5,1,1,1,2,1,3,1,1]]))

[2]


In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]]


In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[78  1]
 [ 4 54]]


0.9635036496350365

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = lr, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.71 %
Standard Deviation: 2.13 %
